name: CI
on: [push]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Jest and RTL
        run: yarn ci:test

      - name: Build files
        run: yarn build

      - name: Start the server
        run: yarn start

      - name: Run Cypress tests
        run: yarn ci:cypress
