name: CI
on: [push]
jobs:
  test:
    name: Jest and RTL tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Jest and RTL
        run: yarn ci:test

      - name: Cypress
        run: yarn ci:startServer
        run: yarn ci:cypress
