name: CI
on: [push]
jobs:
  tests:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run actions/setup-node@v2
        uses: actions/setup-node@v2

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Jest and RTL Tests
        run: yarn ci:test

      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
