name: CI
on: [push]
jobs:
  test:
    name: Jest and RTL tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Jest and RTL
        run: yarn ci:test
      - name: Start Next Dev Server
        run: npx next dev -p 3000

      - name: Cypress
        uses: cypress-io/github-action@v2
      - run: yarn ci:cypress
