name: CI
on: [push]
jobs:
  test:
    name: Jest and RTL tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn
      - name: Jest and RTL
        run: yarn test
